local MovesetData = {}

MovesetData.Moves = {

	-- ── M1 COMBO CHAIN ──────────────────────────────────────────────
	M1_1 = {
		name       = "Jab",
		type       = "combo",
		damage     = 8,
		hitstun    = 0.30,
		knockback  = Vector3.new(0, 0, 14),
		range      = 6,
		animation  = "Jab",
		sfx        = "Punch_Light",
		gore       = "BloodSplatter_Small",
	},
	M1_2 = {
		name       = "Cross",
		type       = "combo",
		damage     = 10,
		hitstun    = 0.35,
		knockback  = Vector3.new(5, 0, 14),
		range      = 6,
		animation  = "Cross",
		sfx        = "Punch_Medium",
		gore       = "BloodSplatter_Medium",
	},
	M1_3 = {
		name       = "Hook",
		type       = "combo",
		damage     = 13,
		hitstun    = 0.40,
		knockback  = Vector3.new(-10, 0, 10),
		range      = 6,
		animation  = "Hook",
		sfx        = "Punch_Heavy",
		gore       = "BloodSplatter_Medium",
	},
	M1_4 = {
		name       = "Uppercut",
		type       = "combo",
		damage     = 16,
		hitstun    = 0.45,
		knockback  = Vector3.new(0, 22, 5),
		range      = 6,
		animation  = "Uppercut",
		sfx        = "Punch_Heavy",
		gore       = "BloodSplatter_Large",
	},
	M1_5 = {
		name         = "Finisher Slam",
		type         = "combo_finisher",
		damage       = 32,
		hitstun      = 1.0,
		knockback    = Vector3.new(0, -55, 90),
		range        = 7,
		animation    = "FinisherSlam",
		sfx          = "Punch_Finisher",
		gore         = "BloodSplatter_Massive",
		screenShake  = true,
		craterOnLand = true,
	},

	-- ── SPECIAL MOVES ───────────────────────────────────────────────
	SonicClap = {
		name        = "Sonic Clap",
		keybind     = "E",
		type        = "special",
		damage      = 25,
		hitstun     = 1.5,
		knockback   = Vector3.new(0, 0, 55),
		range       = 22,
		aoeAngle    = 120,
		cooldown    = 8,
		animation   = "SonicClap",
		sfx         = "SonicClap",
		gore        = "EarBleed",
		description = "Supersonic clap. Stuns all enemies in a wide arc.",
		requiredPL  = 0,
	},
	ViltrumiteRush = {
		name        = "Viltrumite Rush",
		keybind     = "R",
		type        = "special",
		damage      = 42,
		hitstun     = 0.8,
		knockback   = Vector3.new(0, 12, 110),
		range       = 65,
		cooldown    = 12,
		animation   = "ViltrumiteRush",
		sfx         = "SonicBoom",
		gore        = "BloodTrail",
		description = "Charge at a target at supersonic speed.",
		requiredPL  = 5000,
		dashSpeed   = 500,
	},
	EarthShatter = {
		name           = "Earth Shatter",
		keybind        = "F",
		type           = "special",
		damage         = 65,
		hitstun        = 2.0,
		knockback      = Vector3.new(0, 5, 0),
		range          = 18,
		cooldown       = 20,
		animation      = "EarthShatter",
		sfx            = "EarthShatter",
		gore           = "BloodSplatter_Massive",
		description    = "Slam into the ground from the air, shockwave on impact.",
		requiredPL     = 20000,
		requiresFlight = true,
		screenShake    = true,
		craterSize     = 30,
	},
	ThoraxStrike = {
		name        = "Thorax Strike",
		keybind     = "G",
		type        = "special",
		damage      = 85,
		hitstun     = 3.0,
		knockback   = Vector3.new(0, 0, 160),
		range       = 6,
		cooldown    = 25,
		animation   = "ThoraxStrike",
		sfx         = "BoneCrunch",
		gore        = "GoreExplosion",
		description = "Target the Viltrumite weak point. Devastating close-range grab.",
		requiredPL  = 100000,
		isGrab      = true,
	},
	SupremeOverdrive = {
		name              = "Supreme Overdrive",
		keybind           = "T",
		type              = "ultimate",
		damage            = 220,
		hitstun           = 5.0,
		knockback         = Vector3.new(0, 120, 350),
		range             = 8,
		cooldown          = 120,
		animation         = "SupremeOverdrive",
		sfx               = "UltimateImpact",
		gore              = "UltimateGore",
		description       = "The full might of Viltrumite power unleashed.",
		requiredPL        = 500000,
		requiredBloodline = "Pure Viltrumite",
		screenShake       = true,
	},

	-- ── DEFENSIVE ───────────────────────────────────────────────────
	Block = {
		name              = "Block",
		keybind           = "Q",
		type              = "defensive",
		damageReduction   = 0.70,
		perfectParryWindow = 0.2,
		animation         = "Block",
		sfx               = "Block",
	},
}

function MovesetData.Get(name)
	return MovesetData.Moves[name]
end

function MovesetData.GetComboMove(count)
	return MovesetData.Moves["M1_" .. tostring(count)]
end

return MovesetData
